#ifndef UCORE_VERSION_H
#define UCORE_VERSION_H

#define UCORE_LIB_MAJOR 2
#define UCORE_LIB_MINOR 5
#define UCORE_LIB_PATCH 0

#define UCORE_LANG_MAJOR 1
#define UCORE_LANG_MINOR 0
#define UCORE_LANG_PATCH 0

#endif