# build the auto generate config headers

set(header_content "// AUTOGENERATED FROM UNETWORK_CONFIG_HEADER_FILES and then UNETWORK_<PLATFORM>_CONFIG_HEADER_FILES\n// DO NOT EDIT!\n")
string(TOUPPER ${PICO_PLATFORM} PICO_PLATFORM_UPPER)


configure_file(${CMAKE_SOURCE_DIR}/ucore/include/ucore_version.h.in ${CMAKE_SOURCE_DIR}/ucore/include/ucore_version.h)