set(UNETWORK_VERSION_MAJOR 0)
set(UNETWORK_VERSION_MINOR 0)
set(UNETWORK_VERSION_REVISION 1)

set(UNETWORK_VERSION_STRING "${UNETWORK_VERSION_MAJOR}.${UNETWORK_VERSION_MINOR}.${UNETWORK_VERSION_REVISION}")